-- MySQL Script generated by MySQL Workbench
-- Mon May  3 08:59:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plasaria_itools
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `plasaria_itools` ;

-- -----------------------------------------------------
-- Schema plasaria_itools
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plasaria_itools` DEFAULT CHARACTER SET utf8 ;
USE `plasaria_itools` ;

-- -----------------------------------------------------
-- Table `plasaria_itools`.`user_flag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`user_flag` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`user_flag` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `plasaria_itools`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`user_type` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`user_type` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_type_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_user_user_type_updated_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `fk_user_type_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`user` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`user` (
  `id` VARCHAR(30) NOT NULL,
  `user_flag_id` VARCHAR(30) NOT NULL,
  `user_type_id` VARCHAR(30) NOT NULL,
  `toko_id` VARCHAR(45) NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fullname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `nik` VARCHAR(255) NULL,
  `phone` VARCHAR(15) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_flag_idx` (`user_flag_id` ASC) VISIBLE,
  INDEX `fk_user_user_type_user_type_id_idx` (`user_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_flag_user_flag_id`
    FOREIGN KEY (`user_flag_id`)
    REFERENCES `plasaria_itools`.`user_flag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user_type_user_type_id`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `plasaria_itools`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`bank` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`bank` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `code` VARCHAR(3) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `plasaria_itools`.`ecommerce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`ecommerce` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`ecommerce` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `plasaria_itools`.`toko`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`toko` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`toko` (
  `id` VARCHAR(30) NOT NULL,
  `ecommerce_id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `phone_2` VARCHAR(15) NULL,
  `npwp` VARCHAR(15) NULL,
  `bank_id` VARCHAR(30) NULL,
  `no_rek` VARCHAR(45) NULL,
  `cab_bank` VARCHAR(45) NULL,
  `atas_nama` VARCHAR(45) NULL,
  `country_id` VARCHAR(30) NULL,
  `province_id` VARCHAR(30) NULL,
  `city_id` VARCHAR(30) NULL,
  `sub_district_id` VARCHAR(30) NULL,
  `postcode_id` VARCHAR(30) NULL,
  `PIC` VARCHAR(45) NULL,
  `jabatan` VARCHAR(45) NULL,
  `pic_email` VARCHAR(45) NULL,
  `pic_phone` VARCHAR(45) NULL,
  `pic_phone_2` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_toko_ecommerce_bank_id_idx` (`bank_id` ASC) VISIBLE,
  INDEX `fk_toko_ecommerce_ecommerce_id_idx` (`ecommerce_id` ASC) VISIBLE,
  CONSTRAINT `fk_toko_ecommerce_bank_id`
    FOREIGN KEY (`bank_id`)
    REFERENCES `plasaria_itools`.`bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_toko_ecommerce_ecommerce_id`
    FOREIGN KEY (`ecommerce_id`)
    REFERENCES `plasaria_itools`.`ecommerce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`supplier` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`supplier` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `email` VARCHAR(45) NULL,
  `refrensi` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `phone_2` VARCHAR(15) NOT NULL,
  `npwp` VARCHAR(15) NULL,
  `bank_id` VARCHAR(30) NULL,
  `no_rek` VARCHAR(45) NULL,
  `cab_bank` VARCHAR(45) NULL,
  `atas_nama` VARCHAR(45) NULL,
  `country_id` VARCHAR(30) NULL,
  `province_id` VARCHAR(30) NULL,
  `city_id` VARCHAR(30) NULL,
  `sub_district_id` VARCHAR(30) NULL,
  `postcode_id` VARCHAR(30) NULL,
  `detail_alamat` TEXT(255) NULL,
  `pic` VARCHAR(45) NULL,
  `jabatan` VARCHAR(45) NULL,
  `pic_email` VARCHAR(45) NULL,
  `pic_phone` VARCHAR(45) NULL,
  `pic_phone_2` VARCHAR(45) NULL,
  `pic_note` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `plasaria_itools`.`supplier_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`supplier_attachment` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`supplier_attachment` (
  `id` VARCHAR(30) NOT NULL,
  `supplier_id` VARCHAR(30) NOT NULL,
  `file_url` VARCHAR(255) NULL,
  `file_object` VARCHAR(255) NULL,
  `file_real_name` VARCHAR(255) NULL,
  `file_enc_name` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_supplier_attachment_supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_supplier_attachment_supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `plasaria_itools`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`customer` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`customer` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `email` VARCHAR(45) NULL,
  `refrensi` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `phone_2` VARCHAR(15) NOT NULL,
  `npwp` VARCHAR(15) NULL,
  `bank_id` VARCHAR(30) NULL,
  `no_rek` VARCHAR(45) NULL,
  `cab_bank` VARCHAR(45) NULL,
  `atas_nama` VARCHAR(45) NULL,
  `country_id` VARCHAR(30) NULL,
  `province_id` VARCHAR(30) NULL,
  `city_id` VARCHAR(30) NULL,
  `sub_district_id` VARCHAR(30) NULL,
  `postcode_id` VARCHAR(30) NULL,
  `detail_alamat` TEXT(255) NULL,
  `pic` VARCHAR(45) NULL,
  `jabatan` VARCHAR(45) NULL,
  `pic_email` VARCHAR(45) NULL,
  `pic_phone` VARCHAR(45) NULL,
  `pic_phone_2` VARCHAR(45) NULL,
  `pic_note` TEXT(255) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_supplier_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_user_created_by0`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_user_updated_by0`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`customer_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`customer_attachment` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`customer_attachment` (
  `id` VARCHAR(30) NOT NULL,
  `cust_id` VARCHAR(30) NOT NULL,
  `file_url` VARCHAR(255) NULL,
  `file_object` VARCHAR(255) NULL,
  `file_real_name` VARCHAR(255) NULL,
  `file_enc_name` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_supplier_attachment_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_supplier_attachment_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_customer_customer_attachment_cust_id_idx` (`cust_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_customer_attachment_cust_id`
    FOREIGN KEY (`cust_id`)
    REFERENCES `plasaria_itools`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_attachment_user_created_by0`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_attachment_user_updated_by0`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`category_support`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`category_support` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`category_support` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ecommerce_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_ecommerce_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `fk_ecommerce_user_created_by0`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ecommerce_user_updated_by0`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`category_primary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`category_primary` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`category_primary` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ecommerce_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_ecommerce_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `fk_ecommerce_user_created_by00`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ecommerce_user_updated_by00`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`category_sub_first`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`category_sub_first` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`category_sub_first` (
  `id` VARCHAR(30) NOT NULL,
  `category_primary_id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ecommerce_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_ecommerce_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_category_sub_first_category_primary_id_idx` (`category_primary_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_sub_first_user_created_by000`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_sub_first_user_updated_by000`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_sub_first_category_primary_id`
    FOREIGN KEY (`category_primary_id`)
    REFERENCES `plasaria_itools`.`category_primary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`category_sub_second`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`category_sub_second` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`category_sub_second` (
  `id` VARCHAR(30) NOT NULL,
  `category_primary_id` VARCHAR(30) NOT NULL,
  `category_sub_first_id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ecommerce_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_ecommerce_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_category_sub_first_category_primary_id_idx` (`category_primary_id` ASC) VISIBLE,
  INDEX `fk_category_sub_second_category_sub_first_id_idx` (`category_sub_first_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_sub_second_user_created_by0000`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_sub_second_user_updated_by0000`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_sub_second_category_primary_id0`
    FOREIGN KEY (`category_primary_id`)
    REFERENCES `plasaria_itools`.`category_primary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_sub_second_category_sub_first_id`
    FOREIGN KEY (`category_sub_first_id`)
    REFERENCES `plasaria_itools`.`category_sub_first` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`product_quality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`product_quality` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`product_quality` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `plasaria_itools`.`uom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`uom` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`uom` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(3) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `fk_grosir_user_created_by0`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grosir_user_updated_by0`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`product` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`product` (
  `id` VARCHAR(30) NOT NULL,
  `category_primary_id` VARCHAR(30) NOT NULL,
  `category_sub_first_id` VARCHAR(30) NOT NULL,
  `category_sub_second_id` VARCHAR(30) NOT NULL,
  `category_support_id` VARCHAR(30) NOT NULL,
  `product_quality_id` VARCHAR(30) NOT NULL,
  `uom_id` VARCHAR(30) NOT NULL,
  `supplier_id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `retail_price` VARCHAR(30) NOT NULL,
  `stock_min` BIGINT(11) NOT NULL,
  `current_stock` BIGINT(11) NOT NULL,
  `date_of_entry` DATETIME NOT NULL,
  `note` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_product_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_product_category_primary_category_primary_id_idx` (`category_primary_id` ASC) VISIBLE,
  INDEX `fk_product_category_sub_first_category_sub_first_id_idx` (`category_sub_first_id` ASC) VISIBLE,
  INDEX `fk_product_category_sub_second_category_sub_second_id_idx` (`category_sub_second_id` ASC) VISIBLE,
  INDEX `fk_product_category_support_category_support_id_idx` (`category_support_id` ASC) VISIBLE,
  INDEX `fk_product_product_quality_product_quality_id_idx` (`product_quality_id` ASC) VISIBLE,
  INDEX `fk_product_uom_uom_id_idx` (`uom_id` ASC) VISIBLE,
  INDEX `fk_product_supplier_supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category_primary_category_primary_id`
    FOREIGN KEY (`category_primary_id`)
    REFERENCES `plasaria_itools`.`category_primary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category_sub_first_category_sub_first_id`
    FOREIGN KEY (`category_sub_first_id`)
    REFERENCES `plasaria_itools`.`category_sub_first` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category_sub_second_category_sub_second_id`
    FOREIGN KEY (`category_sub_second_id`)
    REFERENCES `plasaria_itools`.`category_sub_second` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category_support_category_support_id`
    FOREIGN KEY (`category_support_id`)
    REFERENCES `plasaria_itools`.`category_support` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_product_quality_product_quality_id`
    FOREIGN KEY (`product_quality_id`)
    REFERENCES `plasaria_itools`.`product_quality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_uom_uom_id`
    FOREIGN KEY (`uom_id`)
    REFERENCES `plasaria_itools`.`uom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_supplier_supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `plasaria_itools`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`grosir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`grosir` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`grosir` (
  `id` VARCHAR(30) NOT NULL,
  `product_id` VARCHAR(30) NOT NULL,
  `min_stock` BIGINT(11) NOT NULL,
  `price` BIGINT(11) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tp_product_quality_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `fk_grosir_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `plasaria_itools`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grosir_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grosir_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`uom_convert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`uom_convert` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`uom_convert` (
  `id` VARCHAR(30) NOT NULL,
  `source_uom` VARCHAR(30) NOT NULL,
  `dest_uom` VARCHAR(30) NOT NULL,
  `value` BIGINT(11) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_uom_convert_uom_source_uom_idx` (`source_uom` ASC) VISIBLE,
  INDEX `fk_uom_convert_uom_dest_uom_idx` (`dest_uom` ASC) VISIBLE,
  CONSTRAINT `fk_uom_user_created_by00`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uom_user_updated_by00`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uom_convert_uom_source_uom`
    FOREIGN KEY (`source_uom`)
    REFERENCES `plasaria_itools`.`uom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uom_convert_uom_dest_uom`
    FOREIGN KEY (`dest_uom`)
    REFERENCES `plasaria_itools`.`uom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`logistic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`logistic` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`logistic` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NOT NULL,
  `phone_2` VARCHAR(15) NOT NULL,
  `npwp` VARCHAR(15) NULL,
  `country_id` VARCHAR(30) NULL,
  `province_id` VARCHAR(30) NULL,
  `city_id` VARCHAR(30) NULL,
  `sub_district_id` VARCHAR(30) NULL,
  `postcode_id` VARCHAR(30) NULL,
  `detail_alamat` TEXT(255) NULL,
  `pic` VARCHAR(45) NULL,
  `jabatan` VARCHAR(45) NULL,
  `pic_email` VARCHAR(45) NULL,
  `pic_phone` VARCHAR(45) NULL,
  `pic_phone_2` VARCHAR(45) NULL,
  `pic_note` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `plasaria_itools`.`tp_bank_logistic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`tp_bank_logistic` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`tp_bank_logistic` (
  `id` VARCHAR(30) NOT NULL,
  `logistic_id` VARCHAR(30) NOT NULL,
  `bank_id` VARCHAR(30) NOT NULL,
  `no_rek` VARCHAR(45) NULL,
  `cab_bank` VARCHAR(45) NULL,
  `atas_nama` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tp_bank_logistic_logistic_logistic_id_idx` (`logistic_id` ASC) VISIBLE,
  INDEX `fk_tp_bank_logistic_bank_bank_id_idx` (`bank_id` ASC) VISIBLE,
  CONSTRAINT `fk_tp_bank_logistic_logistic_logistic_id`
    FOREIGN KEY (`logistic_id`)
    REFERENCES `plasaria_itools`.`logistic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_bank_logistic_bank_bank_id`
    FOREIGN KEY (`bank_id`)
    REFERENCES `plasaria_itools`.`bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`tp_bank_supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`tp_bank_supplier` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`tp_bank_supplier` (
  `id` VARCHAR(30) NOT NULL,
  `supplier_id` VARCHAR(30) NOT NULL,
  `bank_id` VARCHAR(30) NOT NULL,
  `no_rek` VARCHAR(45) NULL,
  `cab_bank` VARCHAR(45) NULL,
  `atas_nama` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tp_bank_logistic_bank_bank_id_idx` (`bank_id` ASC) VISIBLE,
  INDEX `fk_tp_bank_logistic_logistic_logistic_id0_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_tp_bank_supplier_supplier_supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `plasaria_itools`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_bank_supplier_bank_bank_id`
    FOREIGN KEY (`bank_id`)
    REFERENCES `plasaria_itools`.`bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`tp_bank_cust`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`tp_bank_cust` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`tp_bank_cust` (
  `id` VARCHAR(30) NOT NULL,
  `cust_id` VARCHAR(30) NOT NULL,
  `bank_id` VARCHAR(30) NOT NULL,
  `no_rek` VARCHAR(45) NULL,
  `cab_bank` VARCHAR(45) NULL,
  `atas_nama` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tp_bank_logistic_bank_bank_id_idx` (`bank_id` ASC) VISIBLE,
  INDEX `fk_tp_bank_cust_cust_id_idx` (`cust_id` ASC) VISIBLE,
  CONSTRAINT `fk_tp_bank_cust_cust_id`
    FOREIGN KEY (`cust_id`)
    REFERENCES `plasaria_itools`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_bank_supplier_bank_bank_id0`
    FOREIGN KEY (`bank_id`)
    REFERENCES `plasaria_itools`.`bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`logistic_price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`logistic_price` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`logistic_price` (
  `id` VARCHAR(30) NOT NULL,
  `logistic_id` VARCHAR(30) NOT NULL,
  `source_country` VARCHAR(30) NOT NULL,
  `dest_country` VARCHAR(30) NOT NULL,
  `source_city` VARCHAR(30) NOT NULL,
  `dest_city` VARCHAR(30) NOT NULL,
  `service_name` VARCHAR(45) NOT NULL,
  `armada` VARCHAR(45) NOT NULL,
  `via` ENUM('DARAT', 'LAUT', 'UDARA') NOT NULL,
  `sla` DATETIME NOT NULL,
  `price` BIGINT(11) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_logistic_price_logistic_logistic_id_idx` (`logistic_id` ASC) VISIBLE,
  CONSTRAINT `fk_logistic_price_user_created_by00`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logistic_price_user_updated_by00`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logistic_price_logistic_logistic_id`
    FOREIGN KEY (`logistic_id`)
    REFERENCES `plasaria_itools`.`logistic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`purchase_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`purchase_order` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`purchase_order` (
  `id` VARCHAR(30) NOT NULL COMMENT 'JADI NO PO.',
  `cust_id` VARCHAR(30) NOT NULL,
  `note` TEXT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_purchase_order_customer_cust_id_idx` (`cust_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_order_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_order_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_order_customer_cust_id`
    FOREIGN KEY (`cust_id`)
    REFERENCES `plasaria_itools`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`po_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`po_attachment` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`po_attachment` (
  `id` VARCHAR(30) NOT NULL,
  `po_id` VARCHAR(30) NOT NULL,
  `file_url` VARCHAR(255) NULL,
  `file_object` VARCHAR(255) NULL,
  `file_real_name` VARCHAR(255) NULL,
  `file_enc_name` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_po_attachment_purchase_order_po_id_idx` (`po_id` ASC) VISIBLE,
  CONSTRAINT `fk_po_user_created_by00`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_po_user_updated_by00`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_po_attachment_purchase_order_po_id`
    FOREIGN KEY (`po_id`)
    REFERENCES `plasaria_itools`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`po_revision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`po_revision` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`po_revision` (
  `id` VARCHAR(30) NOT NULL,
  `po_id` VARCHAR(30) NOT NULL,
  `revisi_idx` BIGINT(11) NULL,
  `prev_note` TEXT NULL,
  `curr_note` TEXT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_po_attachment_purchase_order_po_id_idx` (`po_id` ASC) VISIBLE,
  CONSTRAINT `fk_po_user_created_by000`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_po_user_updated_by000`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_po_revision_purchase_order_po_id0`
    FOREIGN KEY (`po_id`)
    REFERENCES `plasaria_itools`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`delivery_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`delivery_order` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`delivery_order` (
  `id` VARCHAR(30) NOT NULL COMMENT 'JADI NO PO.',
  `po_id` VARCHAR(30) NOT NULL,
  `date_of_exit` DATETIME NULL,
  `payment_method` VARCHAR(45) NULL,
  `cod` ENUM('0', '1') NULL,
  `pick_up` ENUM('0', '1') NULL,
  `address` TEXT NULL,
  `google_map` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_delivery_order_purchase_order_po_id_idx` (`po_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_order_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_order_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_order_purchase_order_po_id`
    FOREIGN KEY (`po_id`)
    REFERENCES `plasaria_itools`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`tp_product_do`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`tp_product_do` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`tp_product_do` (
  `id` VARCHAR(30) NOT NULL,
  `logistic_price_id` VARCHAR(30) NOT NULL,
  `do_id` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tp_bank_logistic_logistic_logistic_id_idx` (`logistic_price_id` ASC) VISIBLE,
  INDEX `fk_tp_logistic_do_delivery_order_do_id_idx` (`do_id` ASC) VISIBLE,
  INDEX `fk_tp_logistic_do_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_tp_logistic_do_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `fk_tp_logistic_do_logistic_price_logistic_price_id`
    FOREIGN KEY (`logistic_price_id`)
    REFERENCES `plasaria_itools`.`logistic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_logistic_do_delivery_order_do_id`
    FOREIGN KEY (`do_id`)
    REFERENCES `plasaria_itools`.`delivery_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_logistic_do_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_logistic_do_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`invoice` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`invoice` (
  `id` VARCHAR(30) NOT NULL COMMENT 'JADI NO PO.',
  `po_id` VARCHAR(30) NOT NULL,
  `note` TEXT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_delivery_order_purchase_order_po_id_idx` (`po_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_user_updated_by0`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_purchase_order_po_id`
    FOREIGN KEY (`po_id`)
    REFERENCES `plasaria_itools`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`handover`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`handover` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`handover` (
  `id` VARCHAR(30) NOT NULL COMMENT 'JADI NO PO.',
  `do_id` VARCHAR(30) NOT NULL,
  `checker_one` VARCHAR(30) NOT NULL,
  `checker_two` VARCHAR(30) NOT NULL,
  `perihal` VARCHAR(50) NOT NULL,
  `note` TEXT NULL,
  `address` TEXT NOT NULL,
  `google_map` VARCHAR(255) NULL,
  `sender` VARCHAR(45) NOT NULL,
  `correct` ENUM('0', '1') NULL,
  `qty` BIGINT(11) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_handover_delivery_order_do_id_idx` (`do_id` ASC) VISIBLE,
  INDEX `fk_invoice_user_checker_two_idx` (`checker_two` ASC) VISIBLE,
  INDEX `fk_invoice_user_checker_one_idx` (`checker_one` ASC) VISIBLE,
  CONSTRAINT `fk_handover_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handover_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handover_delivery_order_do_id`
    FOREIGN KEY (`do_id`)
    REFERENCES `plasaria_itools`.`delivery_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handover_user_checker_one`
    FOREIGN KEY (`checker_one`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handover_user_checker_two`
    FOREIGN KEY (`checker_two`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`retur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`retur` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`retur` (
  `id` VARCHAR(30) NOT NULL COMMENT 'JADI NO PO.',
  `invoice_id` VARCHAR(30) NOT NULL,
  `checker_one` VARCHAR(30) NOT NULL,
  `checker_two` VARCHAR(30) NOT NULL,
  `perihal` VARCHAR(50) NOT NULL,
  `note` TEXT NULL,
  `address` TEXT NOT NULL,
  `google_map` VARCHAR(255) NULL,
  `sender` VARCHAR(45) NOT NULL,
  `correct` ENUM('0', '1') NULL,
  `qty` BIGINT(11) NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_invoice_user_checker_two_idx` (`checker_two` ASC) VISIBLE,
  INDEX `fk_invoice_user_checker_one_idx` (`checker_one` ASC) VISIBLE,
  INDEX `fk_retur_invoice_invoice_id_idx` (`invoice_id` ASC) VISIBLE,
  CONSTRAINT `fk_retur_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_retur_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_retur_invoice_invoice_id`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `plasaria_itools`.`invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_retur_user_checker_one0`
    FOREIGN KEY (`checker_one`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_retur_user_checker_two0`
    FOREIGN KEY (`checker_two`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`fs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`fs` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`fs` (
  `id` VARCHAR(30) NOT NULL COMMENT 'JADI NO PO.',
  `product_id` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_fs_product_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_fs_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fs_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fs_product_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `plasaria_itools`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`tp_fs_ecommerce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`tp_fs_ecommerce` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`tp_fs_ecommerce` (
  `id` VARCHAR(30) NOT NULL COMMENT 'JADI NO PO.',
  `product_id` VARCHAR(30) NOT NULL,
  `ecommerce_id` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grosir_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_grosir_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_fs_product_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_fs_ecommerce_ecommerce_id_idx` (`ecommerce_id` ASC) VISIBLE,
  CONSTRAINT `fk_fs_ecommerce_user_created_by0`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fs_ecommerce_user_updated_by0`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fs_ecommerce_product_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `plasaria_itools`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fs_ecommerce_ecommerce_id`
    FOREIGN KEY (`ecommerce_id`)
    REFERENCES `plasaria_itools`.`ecommerce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`product_alarm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`product_alarm` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`product_alarm` (
  `id` VARCHAR(30) NOT NULL,
  `handover_id` VARCHAR(30) NOT NULL,
  `expired` DATETIME NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_alarm_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_product_alarm_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_product_alarm_handover_handover_id_idx` (`handover_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_alarm_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_alarm_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_alarm_handover_handover_id`
    FOREIGN KEY (`handover_id`)
    REFERENCES `plasaria_itools`.`handover` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`warning`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`warning` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`warning` (
  `id` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_alarm_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_product_alarm_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `fk_warning_alarm_user_created_by00`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warning_alarm_user_updated_by00`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`tp_warning_product_alarm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`tp_warning_product_alarm` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`tp_warning_product_alarm` (
  `id` VARCHAR(30) NOT NULL,
  `product_alarm_id` VARCHAR(30) NOT NULL,
  `warning_alarm_id` VARCHAR(30) NOT NULL,
  `expired` INT(3) NULL,
  `interval` INT(3) NULL,
  `time` DATETIME NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_alarm_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_product_alarm_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_warning_alarm_product_alarm_product_alarm_id_idx` (`product_alarm_id` ASC) VISIBLE,
  INDEX `fk_tp_warning_product_alarm_warning_warning_id_idx` (`warning_alarm_id` ASC) VISIBLE,
  CONSTRAINT `fk_tp_warning_user_created_by0`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_warning_user_updated_by0`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_warning_product_alarm_product_alarm_id`
    FOREIGN KEY (`product_alarm_id`)
    REFERENCES `plasaria_itools`.`product_alarm` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_warning_product_alarm_warning_warning_id`
    FOREIGN KEY (`warning_alarm_id`)
    REFERENCES `plasaria_itools`.`warning` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`price_intel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`price_intel` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`price_intel` (
  `id` VARCHAR(30) NOT NULL,
  `product_id` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_alarm_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_product_alarm_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_product_alarm_handover_handover_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_alarm_user_created_by0`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_alarm_user_updated_by0`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_alarm_handover_handover_id0`
    FOREIGN KEY (`product_id`)
    REFERENCES `plasaria_itools`.`handover` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`tp_price_intel_ecommerce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`tp_price_intel_ecommerce` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`tp_price_intel_ecommerce` (
  `id` VARCHAR(30) NOT NULL,
  `product_id` VARCHAR(30) NOT NULL,
  `ecommerce_id` VARCHAR(30) NOT NULL,
  `source` ENUM('0', '1') NOT NULL,
  `price` BIGINT(11) NOT NULL,
  `created_at` DATETIME NULL,
  `created_by` VARCHAR(30) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_by` VARCHAR(30) NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_alarm_user_created_by_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_product_alarm_user_updated_by_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_tp_price_intel_ecommerce_ecommerce_id_idx` (`ecommerce_id` ASC) VISIBLE,
  INDEX `fk_tp_price_intel_product_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_tp_price_intel_ecommerce_user_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_price_intel_ecommerce_user_updated_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `plasaria_itools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_price_intel_ecommerce_ecommerce_id`
    FOREIGN KEY (`ecommerce_id`)
    REFERENCES `plasaria_itools`.`ecommerce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_price_intel_ecommerce_product_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `plasaria_itools`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `plasaria_itools`.`sequence_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plasaria_itools`.`sequence_data` ;

CREATE TABLE IF NOT EXISTS `plasaria_itools`.`sequence_data` (
  `id` VARCHAR(30) NOT NULL,
  `sequence_name` VARCHAR(60) NULL,
  `sequence_prefix` VARCHAR(20) NULL,
  `sequence_suffix` VARCHAR(10) NULL,
  `sequence_increment` INT(11) NULL,
  `sequence_min_value` INT(11) NULL,
  `sequence_max_value` BIGINT(20) NULL,
  `sequence_cur_value` BIGINT(20) NULL,
  `sequence_cycle` TINYINT(1) NULL,
  `period` DATE NULL,
  `created_at` DATETIME NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
